### ISSUE TITLE
Variable Custom Attribute

### ISSUE THREAD

**Issue by Preliy** [OpenCommissioning/OC_Assistant#7]
We need to add a custom attribute to TwinCAT variables within the LINK classes. Currently, we are using specific comments to filter variables in ADS searches, but adding an attribute would be a more effective and streamlined approach.

**Comment by lattaai9** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the EtherCatVariable class to include a custom attribute for TwinCAT variables. This change allows for more effective filtering in ADS searches, replacing the previous method of using specific comments.

You can review changes in this commit: https://github.com/lattaai9/OpenCommissioning-OC_Assistant-7/commit/2bcdfc7fbb8fcd7a9c843e758bd1bda0888d94e3.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
